<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Kiwi+Maru:wght@300&display=swap" rel="stylesheet">
    
    <link rel="stylesheet" href="../../public/home.css">

    <title>Home</title>
</head>
<body>
  <section class="header-site parallax">
    <nav>
      <ul>
        <li> 
          <a href="#about"> About </a>
        </li>
        <li>
          <a href="#Store"> Store </a>
        </li>
        <li>
          <a href="#Help"> Help </a>
        </li>
        <li>
          <a href="#contacts"> Contacts </a>
        </li>
        <li>
          <a href="#buy"> <i class="fas fa-shopping-basket" style="font-size: 18px; color: white" > </i> </a>
        </li>
      </ul>
    </nav>
    <header>
      <h1 class="title01"> WELCOME SAFE </h1>
    </header>
  </section>

  <section>
    <header>
        <h1 class="title02"> Introdution </h1>
    </header>
    <div class="container">
      <div class="card">
        <div class="topcard">
          <h2 class="title"> Secure </h2>
          <p class="secondtitle">  Keep up with system and software security updates. </p>
        </div>
        <div class="midia01"></div>
        <div class="bottomCard">
          <p class="bottomTex"> Text </p>
          <div class="actionCard">
            <button class="action"> <i class="fas fa-heart"></i> </button>
            <button class="action"> <i class="fas fa-share-alt"></i> </button>
          </div>
        </div>
      </div>
      <div class="card">
        <div class="topcard">
          <h2 class="title"> Alert </h2>
          <p class="secondtitle"> The Alerts page in Security displays all alerts that have been triggered. </p>
        </div>
        <div class="midia02"></div>
        <div class="bottomCard">
          <p class="bottomTex"> Text </p>
          <div class="actionCard">
            <button class="action"> <i class="fas fa-heart"></i> </button>
            <button class="action"> <i class="fas fa-share-alt"></i> </button>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="header-infor">
  <h1 class="title03"> Freely insurance </h1>
  </section>

  <section>
    <header>
        <h1 class="title02"> Content </h1>
    </header>
    <div class="container">
      <div class="card">
        <div class="topcard">
          <h2 class="title"> Secure </h2>
          <p class="secondtitle">  The contact information is only as secure as your make your account. </p>
        </div>
        <div class="midia03"></div>
        <div class="bottomCard">
          <p class="bottomTex"> Text </p>
          <div class="actionCard">
            <button class="action"> <i class="fas fa-heart"></i> </button>
            <button class="action"> <i class="fas fa-share-alt"></i> </button>
          </div>
        </div>
      </div>
      <div class="card">
        <div class="topcard">
          <h2 class="title"> Alert </h2>
          <p class="secondtitle"> Application security is a broad topic that covers software vulnerabilities in web. </p>
        </div>
        <div class="midia04"></div>
        <div class="bottomCard">
          <p class="bottomTex"> Text </p>
          <div class="actionCard">
            <button class="action"> <i class="fas fa-heart"></i> </button>
            <button class="action"> <i class="fas fa-share-alt"></i> </button>
          </div>
        </div>
      </div>
    </div>
  </section>

  <footer class="footer">
    <div class="content">
      <p class="text"> <a href="#"> Safe -</a> </p>
      <p class="text"> <a href="#"> Sales -</a> </p>
      <p class="text"> <a href="#"> Prolife -</a> </p>
      <p class="text"> <a href="#"> Sign Out -</a> </p>
      <p class="text"> <a href="#"> Contacts </a> </p>
    </div>
    
      <div class="hr"></div>
          <div class="icons">
            <ul class="icons">
              <li> <a href="#" style="font-size: 26px"> <i class="fa fa-facebook" aria-hidden="true"></i> </a> </li>
              <li> <a href="#" style="font-size: 26px"> <i class="fa fa-instagram" aria-hidden="true"></i> </a> </li>
              <li> <a href="#" style="font-size: 26px"> <i class="fa fa-linkedin" aria-hidden="true"></i> </a> </li>
              <li> <a href="#" style="font-size: 26px"> <i class="fa fa-google-plus" aria-hidden="true"></i> </a> </li>
            </ul>
        </div>
      </div>
  </footer>

</body>
<script src="https://kit.fontawesome.com/11ff574ce0.js" crossorigin="anonymous"></script>
</html>