<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Kiwi+Maru:wght@300&display=swap" rel="stylesheet">

	<script src="https://kit.fontawesome.com/a81368914c.js"></script>
    <link rel="stylesheet" href="../../public/login.css">

    <title>Login</title>

</head>
<body>
    <img class="wave" src="../../public/img/wave.png">
        <div class="container">
            <div class="img">
                <img src="../../public/img/message.svg">
            </div>
            <div class="login-content">
                <form action="home" method="post">
                    <img src="../../public/img/avatar.svg">
                    <h2><? echo $title; ?></h2>
                    <div class="input-div">
                        <div class="i">
                            <i class="fas fa-user"></i>
                        </div>
                        <div>
                            <h5><? echo $input_User; ?></h5>
                            <input class="input" type="text" name="Name">
                        </div>
                    </div>
                    <div class="input-div">
                    <div class="i">
                            <i class="fas fa-lock"></i>
                        </div>
                        <div>
                            <h5><? echo $input_Pass; ?></h5>
                            <input class="input" type="password" name="Password">
                        </div>
                    </div>
                    <a href="login/account" style="color: #999;">Create an account?</a>
                    <input type="submit" class="btn" value="Login">
                </form>
            </div>
        </div>
        
    <script type="text/javascript" src="../../public/main.js"></script>
</body>
</html>