<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Kiwi+Maru:wght@300&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="../../public/css/user.css">
    <script src="https://kit.fontawesome.com/a81368914c.js"></script>
    
    <title>adm</title> 
</head>
<body>
    <div class="container">
        <div class="card">
            <div class="topcard">
                <h2 class="title"> Cadastro </h2>
                <?= '<p class="secondtitle">';
                        echo $content;
                    '</p>';
                ?>
            </div>
            <div class="icon"></div>
            <div class="bottomCard">
                <p class="bottomTex"> Nome: <?= $user['Name'];?> </p>
                <p class="bottomTex"> E-mail: <?= $user['Email'];?> </p>
                <p class="bottomTex"> Senha: <?= $user['Password'];?> </p>
                <a type="submit" class="btn" href="/user">Check users</a>
                <div class="actionCard">
                    <button class="action"> <i class="fas fa-comment"></i> </button>
                </div>
            </div>
        </div>
    </div>
</body>
</html>